name: Validate Pull Request

on:
  workflow_dispatch:
  pull_request:
  push:
    branch: main

jobs:
  check_all_examples:
    name: Validate all user-contributed examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      
      - name: Run tests
        run: |
          python tools/validate.py
